modelmaker/modelmaker/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('trainer/', include('trainer.urls')),
    path('admin/', admin.site.urls),
]

modelmaker/trainer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'trainer'

urlpatterns = [
    path('', views.index, name='index'),
    path('setup', views.setup_page, name='setup'),
    path('label', views.label, name='label'),
    path('<int:params_id>/save_categories', views.save_categories, name='save_categories'),
    path('<int:params_id>/training', views.training, name='training'),
    path('<uuid:task_id>/get_training_progress', views.get_training_progress, name='get_training_progress'),

]

modelmaker/trainer/models.py
from django.db import models
from django.forms import ModelForm
import mimetypes
from os.path import splitext
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import filesizeformat
from django.core.validators import validate_image_file_extension
#from django.core.files import File
#from django.core.files.storage import default_storage
#from django.core.files.storage import FileSystemStorage

MAX_FILE_SIZE = 24 * 1024 * 1024 # 24 MBs 
# fs = FileSystemStorage(location='/media/imgs')

# Create your models here.
class ModelTrainingParams(models.Model):
    model_name = models.CharField(max_length=200, unique=True)
    number_of_categories = models.IntegerField(default=2)

    def get_num_categories(self):
        return self.number_of_categories

    def __str__(self):
        return self.model_name

class Category(models.Model):
    model = models.ForeignKey(ModelTrainingParams, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    num_files = models.IntegerField(default=0)
    # file = models.FileField(blank=False, upload_to='PN_files/%Y/%m/%d/', verbose_name="Files", help_text=f'Allowed size is {MAX_FILE_SIZE / (1024*1024)} MBs')

    def __str__(self):
        return self.name
    
    class Meta:
        unique_together = ["model", "name"]

# https://gist.github.com/jrosebr1/2140738
# class FileValidator(object):


class Image(models.Model):
     category = models.ForeignKey(Category, on_delete=models.CASCADE)
    #  validator = FileValidator(max_size=MAX_FILE_SIZE)
     file = models.ImageField(blank=False, 
                            upload_to= 'PN_files/%Y/%m/%d/', 
                            verbose_name="Files", 
                            validators=[validate_image_file_extension],
                            #help_text=f'Allowed size is {MAX_FILE_SIZE / (1024*1024)} MBs'
                            )

# upload_to='PN_files/%Y/%m/%d/'

def path_to_image():
    
    pass

modelmaker/trainer/forms.py
from django import forms
from django.forms import ModelForm, ClearableFileInput
from .models import ModelTrainingParams, Category, Image

# Create ModelTrainingParams form
class TrainingParamForm(ModelForm):
    class Meta:
        model =  ModelTrainingParams
        fields = ('model_name', 'number_of_categories')

class CategoryForm(ModelForm):

    class Meta:
        model =  Category
        exclude = ("model", )
        fields = ('name', ) # whats rendered

class CategoryFileForm(CategoryForm):
    file = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
 
    class Meta(CategoryForm.Meta):
        model = Category
        fields = CategoryForm.Meta.fields   
        widgets =  {
            'images': ClearableFileInput(attrs={'multiple': True}),
        }
        

modelmaker/trainer/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .forms import TrainingParamForm, CategoryForm, CategoryFileForm
from django.forms import formset_factory
from .models import Image, Category, ModelTrainingParams
from .tasks import train_model
from .train import start_training
from celery.result import AsyncResult

def label(request):
    return render(request, 'trainer/label.html')

def training(params_id):
    task_id = train_model.delay(params_id)
    print("Task ID: ", task_id)
    # task_id = start_training(params_id)
    return

def get_training_progress(request, task_id):
    result = AsyncResult(str(task_id))
    response_data = {
        'state': result.state,
        'details': result.info,
    }
    return HttpResponse(json.dumps(response_data), content_type='application/json')


def save_categories(request, params_id):
    trained = False
    if(request.method == "POST"):
        params_model = ModelTrainingParams.objects.get(pk=params_id)
        CategoryFormSet = formset_factory(CategoryFileForm, extra=params_model.get_num_categories())
        formset = CategoryFormSet(request.POST, request.FILES)
        print(request.FILES)
        for form, form_key in zip(formset, request.FILES.keys()): # loop through categories
            if form.is_valid():
                print("saving")
                category = form.save(commit=False)
                category.model = ModelTrainingParams.objects.get(pk=params_id)
                category.save()
                # print(form.clean())
                files = request.FILES.getlist(form_key)
                # print(form_key)
                # print(files)
                for f in files:
                    new_file, created = Image.objects.get_or_create(category=Category(id=category.id), file=f)
                    new_file.save()
            else:
                # temporary you should just render a 
                print("form not valid")
                print(form.errors)
                print(form.clean())

                submitted = True
                error = True
                # get the parameters model and make a form

                return render(request, 'trainer/setup.html', {'params_model':params_model, 'submitted':submitted, 'error':error, 'formset':CategoryFormSet}) 

    task_id = training(params_model.id) 
    return render(request, 'trainer/training.html')
   
def setup_page(request):
    submitted = False
    if(request.method == "POST"):
        params_form= TrainingParamForm(request.POST)
        if params_form.is_valid():
            params_model = params_form.save()
            number_categories = params_form.cleaned_data['number_of_categories']
            CategoryFormSet = formset_factory(CategoryFileForm, extra=number_categories)
            # formset = CategoryFormSet(initial = [{'model_id':params_obj.id}])
            return render(request, 'trainer/setup.html', {'submitted':True, 'formset':CategoryFormSet, 'params_model':params_model})
                
    else:
        params_form = TrainingParamForm()
        if 'submitted' in request.GET:
            submitted = True
            
    return render(request, 'trainer/setup.html', {'params_form':params_form, 'submitted':submitted, 'error': False})

# Create your views here. 
def index(request):
    return render(request, 'trainer/base.html')

modelmaker/trainer/templates/trainer/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'trainer:index' %}">
            <img src="{% static 'logo/betterlogo.svg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top"/>
            TensorMaker
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'trainer:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'trainer:setup' %}">Train</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'trainer:label' %}">Label</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'trainer:setup' %}">Deploy</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Upload</a></li>
                  <li><a class="dropdown-item" href="#">Organize</a></li>
                  <li><a class="dropdown-item" href="#">Annotate</a></li>
                  <li><a class="dropdown-item" href="#">Train</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Deploy</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

modelmaker/trainer/templates/trainer/error.html
{% extends 'trainer/base.html' %}

{% block content %}
<div>
    <center><h1>field entry error</h1></center>
</div>
{% endblock %}

modelmaker/trainer/templates/trainer/label.html
{% extends 'trainer/base.html' %}

{% block content %}
<div class="container">
    <center><h1>Label shit here</h1></center>
</div>
{% endblock %}

modelmaker/trainer/templates/trainer/setup.html
{% extends 'trainer/base.html' %}

{% block content %}
    <!-- Setup Fields-->
    {% if submitted %}
    <div class="container">
        <br />
        <div class="card">
            <div class="card-body">
                <h2><b>Simple Classification Trainer:</b> Setup</h2>
                <center><p>valid file formats: .jpg, .jpeg, .png,(normal image file formats...)</p></center>
                <h4>Model Name:  {{ params_model.model_name }}</h4>
                <h4>Number of Categories: {{ params_model.number_of_categories }} </h4>
                <form action="{% url 'trainer:save_categories' params_model.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <ul class="list-group">
                        {% for form in formset %}
                        <li class="list-group-item">{{ form }}</li>
                        {% endfor %}
                    </ul>
                    {% if error %}
                        <b><p id="badfile"> Upload a valid image. The file you uploaded was either not an image or a corrupted image </p></b>
                    {% endif %}
                    {% comment %} <input type="file" name="myfile"> {% endcomment %}
                    <input type="submit" value="Train" class="btn btn-light">
                </form>   
            </div>       

            </div>
        </div>
    </div>
    {% else %} 
    <div class="container">
        <br />
        <div class="card">
            <div class="card-body">
                <h2><b>Simple Classification Trainer:</b> Setup</h2>
                <br />
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ params_form.as_p }}
                    <input type="submit" value="Submit" class="btn btn-light">
                </form>     
            </div>       
        </div>
    </div>
    {% endif %}
    
{% endblock %}

modelmaker/trainer/templates/trainer/training.html
{% extends 'trainer/base.html' %}

 {% block content %}
 <center><h1> Model is TRAINING...</h1></center>
 {% comment %}
<div>
    
    <div class="container">
        <progress id="file" max="100" value="70"> 70% </progress>
    </div>
    <div id="progress-wrapper">
        <div id="progress-bar" style="background-color: blue; width: 0%;">&nbsp;</div>
        <div id="progress-bar-message">Waiting for training to start...</div>
    </div>
    <script>
        function updateProgress (progressUrl) {
            fetch(progressUrl).then(function(response) {
                response.json().then(function(data) {
                    // update the appropriate UI components

                    setProgress(data.state, data.details);
                    setTimeout(updateProgress, 500, progressUrl);
                });
            });
        }
        var progressUrl = '{% url "trainer:get_training_progress" task_id %}';  // django template usage
        updateProgress(progressUrl);
    </script>
</div>
{% endcomment %}
{% endblock %} 